name: CI
on:
 push:
  branches: 
    - main
  paths:
    - server/**
jobs:
 build:
  runs-on: ubuntu-latest
  strategy: 
    matrix:
      go-version: [1.20]
  steps:
   - name: check the code
     uses: actions/Checkout@v2     
   - name: test
     run: echo "tested"
   - name: setup go
     uses: actions/setup-go@v2
     with:
       go-version: ${{ matrix.go-version }}
     env:
      GO111MODULE: "on"
   - name: check setup
     run: |     
       go mod init instacard
       go mod tidy      
   - name: codebuld    
     run: |
      env GOOS=linux
      go build 'server/get/main.go'
      zip get.zip get
      
   - name: Configure AWS Credentials
     uses: aws-actions/configure-aws-credentials@v1
     with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{secrets.AWS_DEFAULT_REGION}}          
   - name: deploy
     run: |
       aws lambda update-function-code --function-name get --region eu-west-1 --zip-file fileb://get.zip
